name: battle_ship
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  randomstring_dart: ^0.0.4
  flutter_native_splash: ^2.3.1
  uuid: ^4.2.2
  path_provider: ^2.0.15
  dio: ^5.2.1+1
  install_plugin: ^2.1.0
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/battleship.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/battleship.png

flutter:
  uses-material-design: true
  assets:
    - assets/battleship.png
